platform :ios, '7.0'

pod 'SSKeychain'
pod 'SVProgressHUD', :head
pod 'NSDate+TimeAgo'
pod 'SGNavigationProgress'
pod 'MRProgress', '~> 0.2'
pod 'UITableView-NXEmptyView'
pod 'NJKWebViewProgress'
pod 'SVWebViewController', :head
pod 'RDVTabBarController'
pod 'UIView+AutoLayout'
pod 'SLRESTfulCoreData'
pod "MagicalRecord"
pod 'Vertigo'
#pod 'JSQMessagesViewController', :git => 'https://github.com/Triaged/JSQMessagesViewController.git'
pod 'JSQMessagesViewController', :git => 'https://github.com/jma256/JSQMessagesViewController.git', :commit => '38b5a6b30d278f9533831212cceb8b0579ad1634'
#pod 'JSQMessagesViewController'
pod 'UIView+Positioning'
pod 'INTULocationManager'
pod "PMEDatePicker", "~> 0.0.1"
pod 'TCCopyableLabel'
pod 'BlocksKit'
pod 'CMNavBarNotificationView', :git => 'https://github.com/edgurgel/CMNavBarNotificationView.git'
pod 'SGNavigationProgress'
pod 'ECPhoneNumberFormatter', :git => 'https://github.com/enriquez/ECPhoneNumberFormatter.git'
pod 'Mixpanel'
pod 'CocoaLumberjack'
pod 'SinchRTC'
pod 'MZFayeClient'
pod 'MPGNotification', :git => 'https://github.com/jma256/MPGNotification.git'
pod 'FXBlurView'
pod 'MBContactPicker'
pod 'VENTokenField', :git => 'https://github.com/jma256/VENTokenField.git'
pod 'FLEX'
